fix: add X-Access-Key header

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -34,56 +34,33 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: Get JSONbin
-      if: ${{ inputs.method == 'GET' }}
-      id: get
-      uses: fjogeleit/http-request-action@v2
-      with:
-        url: "https://api.jsonbin.io/v3/b/${{ inputs.bin-id }}"
-        method: "GET"
-        customHeaders: '{"X-Master-Key": "${{ inputs.master-key }}", "X-Access-Key": "${{ inputs.access-key }}", "Accept": "application/json", "X-Bin-Meta": "true"}'
-    - if: ${{ inputs.method == 'GET' }}
-      run: echo "JSONBIN_ACTION_BIN_ID=${{ fromJson(steps.get.outputs.response).metadata.id }}" >> "$GITHUB_ENV"
-      shell: sh
-    - name: Create JSONbin
-      if: ${{ inputs.method == 'CREATE' }}
-      id: create
-      uses: fjogeleit/http-request-action@v2
-      with:
-        url: "https://api.jsonbin.io/v3/b"
-        method: "POST"
-        customHeaders: '{"X-Master-Key": "${{ inputs.master-key }}", "X-Access-Key": "${{ inputs.access-key }}", "Accept": "application/json", "X-Bin-Private": "true"}'
-        data: "${{ inputs.body }}"
-    - if: ${{ inputs.method == 'CREATE' }}
-      run: echo "JSONBIN_ACTION_BIN_ID=${{ fromJson(steps.create.outputs.response).metadata.id }}" >> "$GITHUB_ENV"
-      shell: sh
-    - name: Update JSONbin
-      if: ${{ inputs.method == 'UPDATE' }}
-      id: update
-      uses: fjogeleit/http-request-action@v2
-      with:
-        url: "https://api.jsonbin.io/v3/b/${{ inputs.bin-id }}"
-        method: "PUT"
-        customHeaders: '{"X-Master-Key": "${{ inputs.master-key }}", "X-Access-Key": "${{ inputs.access-key }}", "Accept": "application/json", "X-Bin-Versioning": "false"}'
-        data: "${{ inputs.body }}"
-    - if: ${{ inputs.method == 'UPDATE' }}
-      run: echo "JSONBIN_ACTION_BIN_ID=${{ fromJson(steps.update.outputs.response).metadata.parentId }}" >> "$GITHUB_ENV"
-      shell: sh
-    - name: Delete JSONbin
-      if: ${{ inputs.method == 'DELETE' }}
-      id: delete
-      uses: fjogeleit/http-request-action@v2
-      with:
-        url: "https://api.jsonbin.io/v3/b/${{ inputs.bin-id }}"
-        method: "DELETE"
-        customHeaders: '{"X-Master-Key": "${{ inputs.master-key }}", "X-Access-Key": "${{ inputs.access-key }}"}'
-    - if: ${{ inputs.method == 'DELETE' }}
-      run: echo "JSONBIN_ACTION_BIN_ID=${{ fromJson(steps.delete.outputs.response).metadata.id }}" >> "$GITHUB_ENV"
-      shell: sh
-    - name: Set output
-      if: ${{ inputs.method == 'GET' || inputs.method == 'CREATE' || inputs.method == 'UPDATE' || inputs.method == 'DELETE' }}
+    - name: Send JSONbin request
+      if: ${{ contains(fromJSON('["GET", "CREATE", "UPDATE", "DELETE"]'), inputs.method) }}
       id: jsonbin
+      env:
+        INPUT_METHOD: "${{ inputs.method }}"
+        INPUT_MASTER_KEY: "${{ inputs.master-key }}"
+        INPUT_ACCESS_KEY: "${{ inputs.access-key }}"
+        INPUT_BIN_ID: "${{ inputs.bin-id }}"
+        INPUT_BODY: "${{ inputs.body }}"
       run: |
-        echo "bin-id=${JSONBIN_ACTION_BIN_ID}" >> "$GITHUB_OUTPUT"
-        echo "url=https://api.jsonbin.io/v3/b/${JSONBIN_ACTION_BIN_ID}" >> "$GITHUB_OUTPUT"
+        bin_id=$(
+          ${GITHUB_ACTION_PATH}/src/main.sh \
+            "${INPUT_METHOD}" \
+            "${INPUT_MASTER_KEY}" \
+            "${INPUT_ACCESS_KEY}" \
+            "${INPUT_BIN_ID}" \
+            "${INPUT_BODY}"
+        )
+        echo "bin-id=${bin_id}" >> "$GITHUB_OUTPUT"
+        echo "url=https://api.jsonbin.io/v3/b/${bin_id}" >> "$GITHUB_OUTPUT"
+      shell: sh
+    - name: Fail
+      if: ${{ !contains(fromJSON('["GET", "CREATE", "UPDATE", "DELETE"]'), inputs.method) }}
+      env:
+        INPUT_METHOD: "${{ inputs.method }}"
+      run: |
+        message="${INPUT_METHOD} method is not supported. Allowed values: GET, CREATE, UPDATE, DELETE"
+        echo "::error title=Method is not supported::{message}"
+        exit 1
       shell: sh
